version: "3.8"

services:
  db: 
    image: postgres
    container_name: db
    environment:
      DB_HOST_NAME: "${DB_HOST_NAME}"
      POSTGRES_USERNAME: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  server:
    image: pnp_server
    container_name: pnp_server
    build: 
      context: ./server
      dockerfile: /Dockerfile
    environment:
       SERVER_HOST_NAME: "${SERVER_HOST_NAME}"
       DB_HOST_NAME: "${DB_HOST_NAME}"
       POSTGRES_USERNAME: "${POSTGRES_USERNAME}"
       POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    depends_on: 
      - db
    volumes: 
     - ./server:/server
    env_file:
      - .env
    ports: 
     - 3000:3000
  client: 
    image: pnp_client
    container_name: pnp_client
    build: 
      context: ./client
      dockerfile: /Dockerfile
    environment:
      VITE_API_ENDPOINT: "${VITE_API_ENDPOINT}"
    command: sh -c "npm install && npm run dev"
    volumes: 
      - ./client:/client
    depends_on:
      - server
    env_file:
      - .env
    ports:
      - 8080:8080